### ISSUE TITLE
Disassemble code

### ISSUE THREAD

**Issue by ProjectRevoTPP** [martmists/pokediamond#1]
What are we gonna do to disassemble the code?

**Comment by martmists** [comment]
Our only option for now is to slowly port over everything we have in Ghidra; starting with nitro sdk functions, we can port over the asm and/or C and slowly get everything moved over. As for structures and enums, we need a better way to organize them than they currently are.

**Comment by PikalaxALT** [comment]
Working on disassembling the overlays.
00-0B: completed
0C: in progress
0D-56: future

**Comment by PikalaxALT** [comment]
Working on disassembling the overlays.
(Module numbers in decimal)
00-36: completed
37-38: in progress
39-87: future

**Comment by PikalaxALT** [comment]
Overlay progress update
(Module numbers in decimal)
00-41: completed
42-50: in review
51-87: TODO

**Comment by PikalaxALT** [comment]
All code is disassembled.
